[package]
name = "http-api-problem"
version = "0.5.3"
authors = ["Christian Douven <chridou@users.noreply.github.com>"]
description = "A library to create HTTP error response content for APIs based on RFC 7807"
repository = "https://github.com/chridou/http-api-problem"
homepage = "https://github.com/chridou/http-api-problem"
documentation = "https://docs.rs/http-api-problem"
readme = "README.MD"
keywords = ["http", "api", "json", "error", "7807"]
categories = ["web-programming"]
license = "Apache-2.0/MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
iron = { version = "0.6", optional = true }
hyper = { version = "0.11", optional = true }
mime = { version = "0.3", optional = true }
rocket = { version = "0.3", optional = true }

[features]
with_iron = ["iron"]
with_hyper = ["hyper", "mime"]
with_rocket = ["rocket"]
